name: ItemCoder
main: me.jaime29010.itemcoder.Main
author: jaime29010
version: ${project.version}
commands:
  itemcoder:
    usage: The command for using ItemCoder features.
    permission: itemcoder.usage